services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - hae_network
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    # user: "0:0" # you may need to uncomment this line if using Ubuntu or if you expereince permission errors
    restart: unless-stopped
    networks:
      - hae_network
    depends_on:
      - mongo

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - READ_TOKEN=${READ_TOKEN}
      - WRITE_TOKEN=${WRITE_TOKEN}
    depends_on:
      - mongo
    networks:
      - hae_network
    restart: unless-stopped

networks:
  hae_network:
    driver: bridge

volumes:
  postgres-data:
  grafana-data:
  mongodb-data:
