apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --out manifests
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --out manifests
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: MONGO_DB
              value: health-auto-export
            - name: MONGO_HOST
              value: hae-mongo
            - name: MONGO_PASSWORD
              value: password
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: admin
            - name: NODE_ENV
              value: production
            - name: READ_TOKEN
              value: sk-jdo2adhseqxaz0no3esemfqgmamg1tdk
            - name: WRITE_TOKEN
              value: sk-f5Hk7ydmhQq9WY566y5Ea8FyMRyu3euX
          image: server:latest
          name: server
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
